### ISSUE TITLE
Mouse speed in Bloodborne

### ISSUE THREAD

**Issue by Santeys** [kalaposfos13/shadPS4#2]
Hello! Can you pls help me to set up mouse sens, I need to increase it about twice the default. I see there are 3 different params for this, but how exactly and what numbers should I write them down in config? Can you give an example?

**Comment by kalaposfos13** [comment]
Sorry I didn't see this earlier, but if the question still stands, clicking the Controller button, then clicking Help in the new window should help you out.

**Comment by Ein420** [comment]
I've just discovered this fork and now I'm curious, how do I get the mouse working? the only thing that works are the mouse buttons

**Comment by Ein420** [comment]
nvm I found the help section
